### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Project516** [lax1dude/eagler-binary-tools#2]
I mean it’s possible.

**Comment by OrangeMan-432** [comment]
This appears to mainly be for shaders and lighting, not actually modifying the base game, just rendering.

**Comment by catfoolyou** [comment]
Probably not, as those mfs have little to no knowledge of coding and Java

**Comment by catfoolyou** [comment]
Also .mdl is'nt from Eagler, its a format used by some early ID software games (Quake I think) and later some of Valve's games like HL2. So technically you could end up putting Metrocops into Eagler.

**Comment by catfoolyou** [comment]
> > Also .mdl isn't from Eagler, its a format used by some early ID software games (Quake I think) and later some of Valve's games like HL2. So technically you could end up putting Metrocops into Eagler.
> 
> No it is my own format, I just use the same file extension as valve and doom

Oh, I though you used that format, because Minecraft (at least early versions) supported it. There were .mdl test builds of early mc that Notch made, but it got scrapped I think.

**Comment by orphanlol** [comment]
minecraft block sex
> I mean it’s possible.

**Comment by catfoolyou** [comment]
What in the fuck
